name: Weekly update

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Update dependencies
        run: |
          go get -u ./...
          go mod tidy
      - name: Run tests
        run: go test ./...
      - name: Commit changes
        run: |
          git config --local user.email "github@raczylo.com"
          git config --local user.name "Lukasz Raczylo [GitHub:quake-kube]"
          git add .
          git commit -m "Update dependencies"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
